---
title: "Assignment 1: Introduction"
author: "Yared S. Asfaw"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I don't have experience in data analytics, R, and Git, formally and informally; but I am highly interested in the field and thus, working hard to get the best out of the course and other reference materials.

2. Are there any components of the course about which you feel confident?

> Answer: I am interested in and passionate about engaging myself in hands-on exercise to learn theories and practice. Thus, the contents and design of the course matche with my expectation, and make me feel confident over the entire course.  

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am not sure at this point, but I have committed myself to win over any challenge or fear that I will face as we go deep in the course. Moreover, in addition to my effort, I will do my best to take advantage of the resources persons available for the course (Instructure and TAs) at the highest possible level to address my concerns.

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/yared2022/Environmental_Data_Analytics_2022.git


